# required Nerd Font
scan_timeout = 0
add_newline = true

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[➜](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false

[nodejs]
symbol = " "

[os]
disabled = false
style = "bold white"
[os.symbols]
Arch = "[ ](bold #168ECA)"

[rust]
symbol = " "

[time]
# disabled = false

[username]
show_always = true
style_user = '#04d500'
format = '[$user]($style) '
